# Site settings
title: Sparkpipe
email: info@uncharted.software
description: > # this means to ignore newlines until "baseurl:"
  Modular, non-linear pipeline framework for Spark
baseurl: "/sparkpipe-core/" # the subpath of your site, e.g. /blog/
url: "//unchartedsoftware.github.io" # the base hostname & protocol for your site
latest: "0.9.5"

# Build settings
markdown: kramdown
highlighter: pygments

syntax-highlighting:
  enabled : true
  css: syntax.css
